### ISSUE TITLE
Where to install lubridate during automation?

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/protocolsource#57]
No idea which is the best place to ask this question, so I put it here.

When running `check_frontmatter()` in a docker container, it drops the error `Package "lubridate" needed for checking of date. Please install it with 'install.packages("lubridate")'.`.  Not a big deal to install it, but I was wondering: which should be the best place to install this for use in the docker container during the automation?

Some options:
- install it directly in the docker container (docker image)
- adding it to renv in protocolsource so it will be installed automatically in the docker container, together with the needed dependencies

**Comment by hansvancalster** [comment]
I think adding it to renv would be the preferred approach.

**Comment by ElsLommelen** [comment]
Eh, do you mind doing that?

**Comment by hansvancalster** [comment]
Done in [cc78e05](https://github.com/inbo/protocolsource/pull/50/commits/cc78e05c3effe1d1a67b20e16133c4624d597ff9)
