### ISSUE TITLE
branch name versus protocol_code?

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/protocolsource#61]
In the current code, I used two different variables 'branch name' and `protocol_code` to pass to the dockers (of which the branch name can be taken from Github when running the docker inside the GHA).  As these names should be the same (except for the prefix `refs/heads/` used by Github), it should probably be better to derive the `protocol_code` from the branch name inside the docker (using regex), rather than trying to do this in the yaml file?

But in this case it seems more appropriate that the error code that points that the given protocol_code is wrong/non-existing, is replaced by an error message saying that the branch name and protocol_code are different when running a GHA.  (When running locally, it is better to keep the current error.)

Also: maybe we should add a check that verifies if only changes are committed from inside the folder named after the branch, in case of branches that are made to change a protocol?  With starting Github users, or distracted people, this seems a useful addition that avoids changes to be lost unexpectedly (e.g. when accidentally making changes to another protocol in the wrong branch, these changes won't make it to the website) and technical files to be broken (e.g. docker files) without noticing.

On the other hand, we could also make sure that in branches that are not named after a protocol_code, no changes are made in protocols.  This could avoid us making changes to protocols that will never make it to the website, but more importantly: it warns protocol writers that didn't follow the rule of using the protocol_code as a branch name.  (In this situation, no GHA will be run to build the website...)

I don't know if there are similar situations that are not covered yet?

Posted after a discussion with @ThierryO

**Comment by ElsLommelen** [comment]
> On the other hand, we could also make sure that in branches that are not named after a protocol_code, no changes are made in protocols. This could avoid us making changes to protocols that will never make it to the website, but more importantly: it warns protocol writers that didn't follow the rule of using the protocol_code as a branch name. (In this situation, no GHA will be run to build the website...)

I'm wondering: how should we handle this part?  Should we make a dedicated docker that performs this small test, or should we use a generic docker and add the testing code to the yaml itself?  One of the disadvantages of the latter, is that we need `get_path_to_protocol()` from protocolhelper, which forces us to install this package inside the GHA.  On the other hand, the generic Dockerfile that we use for all protocolsource dockers, installs the whole list of packages in `renv.lock`, which is much more than we need in this case.

**Comment by ElsLommelen** [comment]
> Can this be done with a GHA without docker that runs on a push to a branch that does not start with s[fpioa]p? And then fail if there are modified, deleted or new Rmd files in the `source/` folder and its subfolders? I think that could be done using only git commands (no R required).

Oh, yes, that's right, you don't need `get_path_to_protocol()` in this case, they are just not allowed to make changes in the source folder.  In this case we can indeed use the Github docker that checks out the branch (`actions/checkout@v2`).  But I would do it on a pull request to the main from a branch that does not start with s[fpioa]p.

Eh, so in case a branch starts with s[fpioa]p, the check docker can always be performed?  So this branch should always be able to deal with the following tests:
- only make changes in the path given by `get_path_to_protocol(<branchname>)` and `NEWS.md` and `.zenodo.json`
- `check_frontmatter()` and `check_structure()`
- be able to deal with `update_version_number()`



> Is there anything else you want me to do for this issue?

Change the error message as is mentioned in the second paragraph in the start of the issue:



> But in this case it seems more appropriate that the error code that points that the given protocol_code is wrong/non-existing, is replaced by an error message saying that the branch name and protocol_code are different when running a GHA. (When running locally, it is better to keep the current error.)

The situation when the error message should change, is if the environmental variable `CI` is TRUE, so if `Sys.getenv("CI")` exists, a logical is and TRUE is.  (I notice when running this locally, I get an empty string, so that's why I added the suggestion to test if it is a logical.)

**Comment by hansvancalster** [comment]
> But I would do it on a pull request to the main from a branch that does not start with s[fpioa]p.

OK

> Eh, so in case a branch starts with s[fpioa]p, the check docker can always be performed? So this branch should always be able to deal with the following tests:
> - only make changes in the path given by get_path_to_protocol(<branchname>) and NEWS.md and .zenodo.json
> - check_frontmatter() and check_structure()
> - be able to deal with update_version_number()

Yes I think so.

>Change the error message as is mentioned in the second paragraph in the start of the issue:
>The situation when the error message should change, is if the environmental variable CI is TRUE, so if Sys.getenv("CI") exists, a logical is and TRUE is. (I notice when running this locally, I get an empty string, so that's why I added the suggestion to test if it is a logical.)

OK I will make that change in protocolhelper.

**Comment by hansvancalster** [comment]
The error message is now changed in the way you suggested. See [a076b1a](https://github.com/inbo/protocolhelper/pull/85/commits/a076b1a6395ae13eabffdd65f0624195b925f58b). It will be available when v0.4.0 of protocolhelper is released (and added to renv of this repo).

**Comment by hansvancalster** [comment]
@ElsLommelen the last task on your list is also done, so I checked it. This issue can therefor be closed.
