### ISSUE TITLE
integrate releases with zenodo

### ISSUE THREAD

**Issue by hansvancalster** [inbo/protocolsource#7]
Whenever we release protocols, trigger zenodo to archive the repository.

- [X] setup webhook for Zenodo Sandbox on repo `protocolsource`
- [x] successfully test webhook on repo `protocolsource`
- [x] add `.zenodo.json` file on repo `protocolsource`
- [x] re-test webhook with `.zenodo.json` on repo `protocolsource`
- [ ] repeat Sandbox & `.zenodo.json` setup at `protocols` repo
- [x] once `protocolsource` repo is ready to be set for Zenodo releases, replace sandbox webhook by Zenodo webhook
- [x] discard test releases for Zenodo Sandbox from `protocolsource` repo
- [x] once `protocols` repo is ready to be set for Zenodo releases, replace sandbox webhook by Zenodo webhook
- [x] discard test releases for Zenodo Sandbox from `protocols` repo

EDIT: replaced `protocols-website` with `protocols` and `protocols` with `protocolsource`. The rendered version will be in `protocols` repo, the source code in `protocolsource` repo

**Comment by florisvdh** [comment]
@hansvancalster in which stage would you like to start this behaviour? Right away, or would you still like a 'maturation' period to experiment with releases on GitHub before connecting with Zenodo? Releases that appear on Zenodo cannot be removed (unless you contact the Zenodo admins), while they can still be deleted on GitHub. On the other hand, releases that appear on GitHub before connecting Zenodo, should be re-released on GitHub if you still want them transmitted, or must be manually uploaded on Zenodo.

Another approach is to use https://sandbox.zenodo.org if you want experimentation _with Zenodo_ (from time to (long) time, those records are deleted again). Of course the previous notes for https://zenodo.org will remain valid.

**Comment by hansvancalster** [comment]
@florisvdh definitely need a maturation period first. Consider this issue just to be a reminder for the time being.

**Comment by florisvdh** [comment]
Regarding https://github.com/inbo/protocols/issues/3#issuecomment-627316739 it seems useful to set up the trigger for Zenodo-releases as well Shall I do that? I think it will be best to first have a test period with the Zenodo **sandbox**. We could make dummy releases to check if everything works OK (incl website), these releases are to be discarded afterwards (i.e. by deleting the tags or even rewriting some repo history).

Once releases are transmitted to 'actual' Zenodo, they will be made definitive and given a DOI (the only solution in case of mistakes is to contact Zenodo). We don't want rubbish to appear there, and on the other hand we want it to be as complete as possible.

The trigger will be needed for this repo as well as for the protocols-website repository. I can start with this one, and do the same (Zenodo Sandbox) for the other repo once it is in place and when it's clear which event must happen there to trigger Zenodo.

**Comment by hansvancalster** [comment]
Yes, that would be great! Good idea to use Zenodo sandbox environment for testing. I am not familiar with triggers, is the trigger for Zenodo completely separate from the trigger for Travis CI/Github runner to the website repo? Or is some coordination necessary?

I'm not sure if we should also archive the contents of the protocols-website repo to zenodo (the source files seem more important to me)? Maybe this can be done infrequently - say once a year or  so.

**Comment by florisvdh** [comment]
They will be separate. Of course both will happen simultaneously when they occur for the same events in a repo. Actually it is called 'webhook':

> Webhooks allow external services to be notified when certain events happen. When the specified events happen, we’ll send a POST request to each of the URLs you provide. Learn more in our [Webhooks Guide](https://developer.github.com/webhooks/).

**Comment by florisvdh** [comment]
> I'm not sure if we should also archive the contents of the protocols-website repo to zenodo

It was my interpretation of the branching model :wink: Anyway, it is very easy to set it up, and it is easier to do it for all releases than to manually switch off and on the webhook to prevent some releases to be transmitted.

Each new release will be a version within the same Zenodo record, which itself stands for one Github repo (one record for `protocols` repo, and another for `protocols-website` if you like). So the administrative burden in GitHub and Zenodo would be minimal.

On the other hand, I now realize that it would be incremental versions for `protocols-website`, as all older protocols are still in it. 

- Another approach would be to have the latest compiled protocols in a separate repo - i.e. no older protocols, no website. I think we touched that idea as well while discussing the branching model. Perhaps that would be more logical to release in Zenodo?

**Comment by hansvancalster** [comment]
I think we decided that the website should have all versions of protocols, because field-workers may need to have access to specific versions in some monitoring projects. So I would stick to the current implementation idea and indeed have webhooks that trigger Zenodo for both the protocols and protocols-website repo.

**Comment by florisvdh** [comment]
- [X] setup webhook for Zenodo Sandbox
- [ ] successfully test webhook
- [ ] add `.zenodo.json` file
- [ ] re-test webhook with `.zenodo.json`
- [ ] repeat Sandbox & `.zenodo.json` setup at `protocols-website` repo
- [ ] once `protocols` repo is ready to be set for Zenodo releases, replace webhook by Zenodo webhook
- [ ] once `protocols-website` repo is ready to be set for Zenodo releases, replace webhook by Zenodo webhook

**Comment by florisvdh** [comment]
@hansvancalster moved my to-do list inside your first comment, so that a progress bar appears in the list of issues

**Comment by florisvdh** [comment]
@hansvancalster I suggest to also insert a version-independent Zenodo badge at the front of the Readme.
